name: chat_app
description: Simple Chat App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # For State managment
  flutter_bloc: ^6.0.6
  formz: ^0.3.1
  equatable: ^1.2.5
  hydrated_bloc: ^6.0.2
  # Plugins
  local_auth: ^0.6.3+2
  # Repositories`
  socket_repository:
    path: packages/socket_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linting
  pedantic: ^1.9.2
  # Logging
  logger: ^0.9.4

flutter:
  uses-material-design: true
